package:
  name: plot_ay
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - plot_ay

about:
  home: add_url_here
  license: MIT License
